version: '3'

services:
  app:
    tty: true
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${TARGET}
      args:
        - DOCKER_USER_UID=${DOCKER_USER_UID}
        - DOCKER_USER_NAME=${DOCKER_USER_NAME}
        - DOCKER_HOST_PORT=${DOCKER_HOST_PORT}
        - SERVER_PORT=${SERVER_PORT}
        - DOCKER_WORK_DIR=${DOCKER_WORK_DIR}
        - DOCKER_LABEL_KEY=${DOCKER_LABEL_KEY}
        - DOCKER_LABEL_VALUE=${DOCKER_LABEL_VALUE}
        - NPM_TOKEN=${NPM_TOKEN}
        - YARN_TOKEN=${YARN_TOKEN}
        - TARGET=${TARGET}
        - GIT_CONFIG_USER_NAME=${GIT_CONFIG_USER_NAME}
        - GIT_CONFIG_USER_EMAIL=${GIT_CONFIG_USER_EMAIL}

    container_name: ${APP_NAME}-${NODE_ENV}
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    secrets:
      - npmrc
    command: sh -c "yarn test:cov && yarn build && yarn pack && yarn publish --new-version $(./docker/current-version.sh)"

    volumes:
      - ./:${DOCKER_WORK_DIR}

    ports:
      - ${DOCKER_HOST_PORT}:${SERVER_PORT}

    networks:
      _network:
        ipv4_address: 12.11.1.3

networks:
  _network:
    driver: bridge
    name: ${DOCKER_IMAGE_NAME}_network
    ipam:
      config:
        - subnet: 12.11.1.0/24
          gateway: 12.11.1.1

secrets:
  npmrc:
    file: ./.npmrc
