name: Node CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x', '18.x']

    steps:
    - uses: actions/checkout@v3
    - name: Create folder
      run: |
        mkdir -p coverage

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
    - run: yarn test:cov
