name: Publish Release
on:
  workflow_run:
    workflows: ["Format and Tests"]
    types:
      - completed
    push:

  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        title: ${{ github.event.head_commit.message }}
