name: Release
on:
  pull_request:
    types:
      - opened
    branches:
      - 'releases/**'

jobs:
  build:
    if: success()

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x']

    steps:
    - uses: actions/checkout@v3
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}

      run: |
        echo set-output name=short_ref::${GITHUB_REF#refs/*/}
        echo ${{ steps.vars.outputs.short_ref }}


# gh release create ${{ github.ref }} --generate-notes
