name: Test
on:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.yarnpkg.com'
      - run: |
          chmod -R +x ./docker
          ./docker/yarn-publish.sh
        shell: bash
        env:
          YARN_TOKEN: ${{ secrets.GH_TOKEN.YARN_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN.NPM_TOKEN }}
